# Generated by Django 5.1.1 on 2024-09-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feelings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mood_intensity',
        ),
    ]
